"""
Shared environment loading utilities.

Single source of truth for loading and parsing environment files.
"""

import os
from pathlib import Path

CONFIG_DIR = Path.home() / ".config" / "ai-mm"
ENV_FILE = CONFIG_DIR / "env"


def parse_env_lines(text: str) -> dict[str, str]:
    """Parse environment file content into a dictionary.

    Args:
        text: Content of an environment file

    Returns:
        Dictionary mapping variable names to values
    """
    env_vars = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key.startswith("export "):
            key = key[7:]
        value = value.strip().strip('"').strip("'")
        if value and value not in ("your_github_token_here", "..."):
            env_vars[key] = value
    return env_vars


def load_env_file(path: Path | None = None) -> dict[str, str]:
    """Load environment variables from file.

    Args:
        path: Path to env file (defaults to ~/.config/ai-mm/env)

    Returns:
        Dictionary mapping variable names to values
    """
    env_path = path or ENV_FILE
    if not env_path.exists():
        return {}
    with open(env_path) as f:
        return parse_env_lines(f.read())


def apply_env(env_vars: dict[str, str], overwrite: bool = False) -> None:
    """Apply environment variables to os.environ.

    Args:
        env_vars: Dictionary of environment variables
        overwrite: If True, overwrite existing values
    """
    for key, value in env_vars.items():
        if overwrite or key not in os.environ:
            os.environ[key] = value


def save_env_file(env_vars: dict[str, str], path: Path | None = None) -> None:
    """Save environment variables to file.

    Args:
        env_vars: Dictionary of environment variables
        path: Path to env file (defaults to ~/.config/ai-mm/env)
    """
    env_path = path or ENV_FILE
    env_path.parent.mkdir(parents=True, exist_ok=True)

    with open(env_path, "w") as f:
        f.write("# AI Tool API Keys\n")
        f.write("# Generated by 'ai config'\n\n")
        for key, value in sorted(env_vars.items()):
            f.write(f'export {key}="{value}"\n')

    env_path.chmod(0o600)
